// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpvNyl_bSOi3KrRI7rcm2UxZLe1QKBlFQ',
    appId: '1:235141661972:web:952a94a144d377a916ee01',
    messagingSenderId: '235141661972',
    projectId: 'notification-test-957a1',
    authDomain: 'notification-test-957a1.firebaseapp.com',
    storageBucket: 'notification-test-957a1.appspot.com',
    measurementId: 'G-PZG9XHV3SF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAezEjkutq_0qYYLENYGlXj7gyqVXLjnNo',
    appId: '1:235141661972:android:ebc17d67ed4e1ff916ee01',
    messagingSenderId: '235141661972',
    projectId: 'notification-test-957a1',
    storageBucket: 'notification-test-957a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCowyNhhGgjJWhJD4QHFDdnqMbc2upDmvs',
    appId: '1:235141661972:ios:d1abde661b1bf59116ee01',
    messagingSenderId: '235141661972',
    projectId: 'notification-test-957a1',
    storageBucket: 'notification-test-957a1.appspot.com',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCowyNhhGgjJWhJD4QHFDdnqMbc2upDmvs',
    appId: '1:235141661972:ios:d1abde661b1bf59116ee01',
    messagingSenderId: '235141661972',
    projectId: 'notification-test-957a1',
    storageBucket: 'notification-test-957a1.appspot.com',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpvNyl_bSOi3KrRI7rcm2UxZLe1QKBlFQ',
    appId: '1:235141661972:web:7ce487452023f73c16ee01',
    messagingSenderId: '235141661972',
    projectId: 'notification-test-957a1',
    authDomain: 'notification-test-957a1.firebaseapp.com',
    storageBucket: 'notification-test-957a1.appspot.com',
    measurementId: 'G-3S5C87Q4XV',
  );
}
